name: build-pr
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get Pull Request Number
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{github.token}}
        script: |
          const core = require('@actions/core')
          const prNumber = context.payload.number;
          core.exportVariable('PULL_NUMBER', prNumber);
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: NPM Install
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Install Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: farmers-anonymous
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
      
    - name: Upload index.html
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.html gs://farmer-hosting/prs/$PULL_NUMBER/index.html
    
    - name: Upload index.js
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.js gs://farmer-hosting/prs/$PULL_NUMBER/index.js
    
    - name: Upload config.json
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./config.json gs://farmer-hosting/prs/$PULL_NUMBER/config.json
