name: build
on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: NPM Install
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Install Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: farmers-anonymous
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
        
    - name: Upload index.html
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.html gs://farmer-hosting/branches/develop/index.html
    
    - name: Upload index.js
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.js gs://farmer-hosting/branches/develop/index.js

    - name: Upload config.json
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp ./config.json gs://farmer-hosting/branches/develop/config.json

    - name: Upload fonts
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp -r ./fonts gs://farmer-hosting/branches/develop/fonts
      
    - name: Upload assets
      run: gsutil -h "Cache-Control:no-cache, max-age=0" cp -r ./assets gs://farmer-hosting/branches/develop/assets