name: build
on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: NPM Install
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Upload index.html
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: farmers-anonymous
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args:
          -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.html gs://farmer-hosting/branches/develop/index.html
    
    - name: Upload index.js
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: farmers-anonymous
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args: 
          -h "Cache-Control:no-cache, max-age=0" cp ./dist/index.js gs://farmer-hosting/branches/develop/index.js
